"""empty message

Revision ID: 427f78b6ce30
Revises: 
Create Date: 2018-05-08 19:42:18.488885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427f78b6ce30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('locale', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'locale')
    # ### end Alembic commands ###
